

- name: "Update Apt Cache"
  apt:
    update_cache: yes
  tags: installation

- name: "Install Common packages"
  apt:
    name: ['python3', 'runc', 'python-pip', 'docker.io', 'python3-venv', 'docker-compose', 'git', 'zsh', 'nano', 'autojump']
    state: latest
  tags: installation, packages

- name: "Python Docker"
  pip:
    name:
      - docker
  tags: python
