all:
  children:
    RPI:
      hosts:
        192.168.187.73:
          ansible_user: pi
          system_hostname: evcc
          ufw_rules:
            - { rule: "allow", port: "22", proto: "tcp" }
            - { rule: "allow", port: "7070", proto: "tcp" }
          ntpserver: "192.168.187.1"
          autostart_user: "pi"
          xkeyboardlayout: "de"
          chrome_url: "http://localhost:7070"
          interface: "eth0"
          ipaddress: "192.168.0.1/24"
          routers: "192.168.187.1"
          dns_servers: "192.168.187.36"
          lcd_type: MPI3501
          lcd_rotate: 90
    EVCC:
      hosts:
        192.168.187.73:
          ansible_user: pi
          autostart_user: "pi"
          xkeyboardlayout: "de"
          chrome_url: "http://localhost:7070"
          interface: "eth0"
          ipaddress: "192.168.0.1/24"
          routers: "192.168.187.1"
          dns_servers: "192.168.187.36"
          lcd_type: MPI3501
          lcd_rotate: 270
